name: Run Migration

on:
  workflow_dispatch:
  push:
    tags:
      - "OP.[0-9]?[0-9]?[0-9]?[0-9]?.[0-9]?[0-9]?.[0-9]?[0-9]?"
    branches:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Build Project Artifacts
      #   run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Deploy Project Artifacts to Vercel
      #   id: deploy
      #   run: |
      #     url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
      #     echo "name=url::$url" >> $GITHUB_OUTPUT

      - name: Check vercel scope
        run: vercel switch --scope=${{ secrets.VERCEL_TOKEN }}
      - name: Alias Preview Deployment
        run: vercel alias nextjs-blog-tau-sepia-23.vercel.app  https://nextjs-blog-58zh97i22-hasanism404-gmailcoms-projects.vercel.app --token=${{ secrets.VERCEL_TOKEN }}
